# permissions for end users to view googlecloudpubsubtopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlecloudpubsubtopic-viewer-role
rules:
- apiGroups:
  - pubsuboperator.quipper.github.io
  resources:
  - googlecloudpubsubtopics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pubsuboperator.quipper.github.io
  resources:
  - googlecloudpubsubtopics/status
  verbs:
  - get
