# permissions for end users to view googlecloudpubsubsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: googlecloudpubsubsubscription-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: google-cloud-pubsub-operator
    app.kubernetes.io/part-of: google-cloud-pubsub-operator
    app.kubernetes.io/managed-by: kustomize
  name: googlecloudpubsubsubscription-viewer-role
rules:
- apiGroups:
  - pubsuboperator.quipper.github.io
  resources:
  - googlecloudpubsubsubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pubsuboperator.quipper.github.io
  resources:
  - googlecloudpubsubsubscriptions/status
  verbs:
  - get
