# permissions for end users to edit googlecloudpubsubtopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlecloudpubsubtopic-editor-role
rules:
- apiGroups:
  - pubsuboperator.quipper.github.io
  resources:
  - googlecloudpubsubtopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pubsuboperator.quipper.github.io
  resources:
  - googlecloudpubsubtopics/status
  verbs:
  - get
