---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - googlecloudpubsuboperator.quipper.github.io
  resources:
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - googlecloudpubsuboperator.quipper.github.io
  resources:
  - subscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - googlecloudpubsuboperator.quipper.github.io
  resources:
  - subscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - googlecloudpubsuboperator.quipper.github.io
  resources:
  - topics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - googlecloudpubsuboperator.quipper.github.io
  resources:
  - topics/finalizers
  verbs:
  - update
- apiGroups:
  - googlecloudpubsuboperator.quipper.github.io
  resources:
  - topics/status
  verbs:
  - get
  - patch
  - update
