name: docker

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker.yaml
      - Dockerfile
      - go.*
      - main.go
      - api/**
      - controllers/**
      - pkg/**
    tags:
      - v*
  pull_request:
    paths:
      - .github/workflows/docker.yaml
      - Dockerfile
      - go.*
      - main.go
      - api/**
      - controllers/**
      - pkg/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - run: make -C e2e_test cluster

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          # set outputs.tags to single tag
          flavor: latest=false
      - uses: int128/wait-for-docker-image-action@v1
        with:
          tags: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test deploy
        env:
          CONTROLLER_IMAGE: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test test

      - run: make -C e2e_test logs-controller
        if: always()
