name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - Makefile
      - '**.go'
      - go.*
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - Makefile
      - '**.go'
      - go.*

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go mod tidy
      - run: make fmt
      - run: make generate manifests
      - uses: int128/update-generated-files-action@f6dc44e35ce252932e9018f1c38d1e2a4ff80e14 # v2.60.0

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make test
      - run: make lint
