name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - '**.go'
      - go.*
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - '**.go'
      - go.*

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: false # by golangci-lint-action
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.2
          args: --timeout=3m

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
      - run: go mod tidy
      - run: make fmt
      - run: make generate manifests
      - uses: int128/update-generated-files-action@v2

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
      - run: make test
