name: release

on:
  push:
    tags:
      - v*
  pull_request:
    paths:
      - config/**
      - .github/workflows/release.yaml

jobs:
  manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - run: kustomize edit set image controller='ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
        working-directory: config/manager
      - run: kustomize build config/default > /tmp/google-cloud-pubsub-operator.yaml
      - run: cat /tmp/google-cloud-pubsub-operator.yaml

      - if: github.ref_type == 'tag'
        run: gh release upload '${{ github.ref_name }}' /tmp/google-cloud-pubsub-operator.yaml --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
